USE [master]
GO
/****** Object:  Database [WSSDepartments]    Script Date: 27.05.2022 8:22:20 ******/
CREATE DATABASE [WSSDepartments]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WSSDepartments', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WSSDepartments.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WSSDepartments_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WSSDepartments_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WSSDepartments] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WSSDepartments].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WSSDepartments] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WSSDepartments] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WSSDepartments] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WSSDepartments] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WSSDepartments] SET ARITHABORT OFF 
GO
ALTER DATABASE [WSSDepartments] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WSSDepartments] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WSSDepartments] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WSSDepartments] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WSSDepartments] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WSSDepartments] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WSSDepartments] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WSSDepartments] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WSSDepartments] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WSSDepartments] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WSSDepartments] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WSSDepartments] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WSSDepartments] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WSSDepartments] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WSSDepartments] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WSSDepartments] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WSSDepartments] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WSSDepartments] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WSSDepartments] SET  MULTI_USER 
GO
ALTER DATABASE [WSSDepartments] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WSSDepartments] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WSSDepartments] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WSSDepartments] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WSSDepartments] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WSSDepartments] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WSSDepartments] SET QUERY_STORE = OFF
GO
USE [WSSDepartments]
GO
/****** Object:  Table [dbo].[Companies]    Script Date: 27.05.2022 8:22:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companies](
	[CompanyId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nchar](2000) NULL,
 CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 27.05.2022 8:22:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departments](
	[DepartmentId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](2000) NULL,
	[CompanyId] [int] NOT NULL,
 CONSTRAINT [PK_Departments] PRIMARY KEY CLUSTERED 
(
	[DepartmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Divisions]    Script Date: 27.05.2022 8:22:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Divisions](
	[DivisionId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](2000) NULL,
	[DepartmentId] [int] NOT NULL,
 CONSTRAINT [PK_Divisions] PRIMARY KEY CLUSTERED 
(
	[DivisionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Departments]  WITH CHECK ADD  CONSTRAINT [FK_Departments_Companies] FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Companies] ([CompanyId])
GO
ALTER TABLE [dbo].[Departments] CHECK CONSTRAINT [FK_Departments_Companies]
GO
ALTER TABLE [dbo].[Divisions]  WITH CHECK ADD  CONSTRAINT [FK_Divisions_Departments] FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[Departments] ([DepartmentId])
GO
ALTER TABLE [dbo].[Divisions] CHECK CONSTRAINT [FK_Divisions_Departments]
GO
USE [master]
GO
ALTER DATABASE [WSSDepartments] SET  READ_WRITE 
GO
